# Generated by Django 5.2.3 on 2025-06-22 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_transaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="type",
            field=models.CharField(
                choices=[("charge", "Charge"), ("payment", "Payment")],
                default="charge",
                max_length=10,
            ),
        ),
    ]
